// Code generated by hertz generator.

package main

import (
	"flag"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

var port = flag.Int64("port", 8888, "ws listen port")

func main() {
	flag.Parse()
	h := server.Default(server.WithHostPorts(fmt.Sprintf(":%d", *port)))

	register(h)

	h.Spin()
}
