// Code generated by hertz generator.

package dcdn_seed

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _seed_managerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportseedallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdownloadtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sdkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfidpeerMw() []app.HandlerFunc {
	// your code...
	return nil
}
